spring:
  application:
    name: zuulGatewayApplication
server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    
zuul:
  routes:
    user:
      path: /user/**
      service-id: UserDiscoveryClient
    note:
      path: /note/**
      service-id: NoteDiscoveryClient
    sensitive-Headers: userId
      
ribbon:
  ConnectTimeout: 2080000
  ReadTimeout: 30000

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 1000000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
              timeoutInMilliseconds: 100000


  host:
    max-total-connections: 10000
    max-per-route-connections: 50

 